### ISSUE TITLE
Sobre la instalación, README.md 

### ISSUE THREAD

**Issue by miguelmcb** [mar-esther23/rgriffin#1]
Además de instalar rJava, se debe instalar R.
En particular, parece que  la instalación en mi caso (Ubuntu 18.04) requiere varios pasos. Al menos:

https://linuxize.com/post/how-to-install-r-on-ubuntu-18-04/
https://www.r-bloggers.com/installing-rjava-on-ubuntu/

Quizás conviene que la guía de instalación se divida por plataformas:
Linux
Windows
Mac

**Comment by mar-esther23** [comment]
Hecho. Lo puse en issues y agregue link al README
